### ISSUE TITLE
find restaurant api and get needed auth

### ISSUE THREAD

**Issue by MacroWil** [zachmshort/Brypamaza#7]

**Comment by pmulville** [comment]
Client ID
rw1AwYGjVyS76ZJka2-ZQw


API Key
xT-Q8GoFHqB3EPJud57dLBhBxJRLPa5OLSR45LVi8eqa626nORl27JKyYGVbmUxzIiadW3rFPt3-_NTSbniCHlRLkWnQz2TwieOaHGRhs_MUL7V_jo7dT8Fer91wZXYx

Yelp API
